import { GetServerSidePropsContext } from "next";
import Head from "next/head";
import Image from "next/image";

//Components
import { Header } from "@/components/Headers";
import { TopBar } from "@/components/Topbar";
import { HomeHeroCategories } from "@/components/HomeHeroCategories";
import { AdvantageSection } from "../components/AdvantageSection";
import { HomeProductsGrid } from "@/components/HomeProductsGrid";
import { Promobanner } from "@/components/PromoBanner";

//Models

import { Categories } from "@/models/Categories";

//CHakra UI
import {
  Box,
  Button,
  Container,
  FormControl,
  Heading,
  Input,
  SimpleGrid,
  Text,
  Grid,
  Flex,
} from "@chakra-ui/react";

//Images
import banner1 from "/public/banner-new-season.jpg";
import banner2 from "/public/banner-sale.jpg";
import WomanStanding from "/public/woman-standing.png";
import MenWalking from "/public/men-walking.png";

//Utilities
import {
  GroupedProducts,
  groupProductsByCategory,
} from "@/utils/groupProductsByCategory";

export type Product = {
  id: number;
  title: string;
  price: number;
  description: string;
  category: string;
  image: string;
  rating: {
    rate: number;
    count: number;
  };
};

type Props = {
  products: Product[];
  categories: Categories[];
  productsGroupedByCategory: GroupedProducts;
};

// this is executhe in the client side

export default function Home({
  products,
  categories,
  productsGroupedByCategory,
}: Props) {
  return (
    <>
      <Head>
        <title>E-Commerce Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TopBar />
      <Box marginBottom="2rem">
        <Header />
      </Box>
      <main>
        <Container>
          <HomeHeroCategories categories={categories}></HomeHeroCategories>
          <AdvantageSection />
        </Container>

        <Container padding="0">
          {Object.entries(productsGroupedByCategory).map(
            ([category, products]) => {
              return (
                <Box key={category} marginBottom="4rem">
                  <Heading
                    as="h2"
                    size="md"
                    textTransform="uppercase"
                    margin={{
                      base: "0 0 1rem 1rem",
                      md: "0 0 1.5rem 0",
                    }}
                  >
                    {category}
                  </Heading>
                  <HomeProductsGrid products={products} />
                </Box>
              );
            }
          )}
        </Container>

        <Container>
          <SimpleGrid
            minChildWidth="320px"
            spacing={{
              base: "1rem",
              md: "2rem",
            }}
          >
            <Promobanner image={banner1}>
              <Text fontSize="sm" color={"gray.500"}>
                New Season
              </Text>
              <Text fontSize="lg" whiteSpace="nowrap">
                LookBook Collection
              </Text>
            </Promobanner>

            <Promobanner image={banner2}>
              <Text fontSize="sm" color={"gray.500"}>
                Sale
              </Text>
              <Text fontSize="lg" whiteSpace="nowrap">
                get up to{" "}
                <Text as="span" color={"red"}>
                  50% off
                </Text>
              </Text>
            </Promobanner>
          </SimpleGrid>
        </Container>
        <Container
          background={"linear-gradient(180deg, #F3F2F2 0%, #DCDBDB 100%); "}
          m={{
            base: "14.75rem 0 0 ",
            md: "2rem auto",
          }}
          p={{
            base: "1.5rem",
            md: "3.55rem",
          }}
          maxW={"100%"}
          position={"relative"}
        >
          <Box
            position={"absolute"}
            w={{
              base: "128px",
              md: "311px",
            }}
            h={{
              base: "242px",
              md: "545px",
            }}
            left={{
              base: "1.5rem",
              md: "50%",
            }}
            top={{
              base: `calc(-242px + 1.5rem)`,
              md: "initial",
            }}
            bottom={{
              md: "0",
            }}
            transform={{
              md: "translateX(-530px)",
            }}
          >
            <Image
              src={WomanStanding}
              alt=""
              fill={true}
              style={{ objectFit: "cover" }}
            />
          </Box>
          <Box
            position={"absolute"}
            w={{
              base: "99px",
              md: "219px",
            }}
            h={{
              base: "236px",
              md: "524px",
            }}
            top={{
              base: `calc(-236px + 1.5rem)`,
              md: "initial",
            }}
            bottom={{
              md: "0",
            }}
            right={{
              base: "2rem",
              md: "50%",
            }}
            transform={{
              md: "translateX(470px)",
            }}
          >
            <Image
              src={MenWalking}
              alt=""
              fill={true}
              style={{ objectFit: "cover" }}
            />
          </Box>

          <Flex
            height={{
              md: "28.75rem",
            }}
            m={"auto"}
            maxW={"33rem"}
            as="article"
            bgColor={"white"}
            p={"2rem"}
          >
            <Grid maxW={"22rem"} textAlign={"center"} m="auto" gap={"2rem"}>
              <header>
                <Heading size={"sm"} textTransform={"uppercase"} color={"gray"}>
                  Special Offer
                </Heading>
                <Heading size={"xl"} textTransform={"uppercase"}>
                  Subscribe and{" "}
                  <Text as="span" color={"red"}>
                    get 10% off
                  </Text>
                </Heading>
              </header>
              <Grid as="form" action="" gap={"1.5rem"}>
                <FormControl>
                  <Input
                    height={"4rem"}
                    textAlign={"inherit"}
                    borderRadius={"0"}
                    type="email"
                    placeholder={"Enter your e-mail"}
                    backgroundColor={"gray.100"}
                  />
                </FormControl>
                <Button
                  bgColor={"black"}
                  height={"4rem"}
                  width={"100%"}
                  textTransform={"uppercase"}
                  size={"lg"}
                >
                  Subscribe
                </Button>
              </Grid>
            </Grid>
          </Flex>
        </Container>
      </main>
    </>
  );
}
// This happen in the server side.
export async function getServerSideProps(contex: GetServerSidePropsContext) {
  const products = await fetch("https://fakestoreapi.com/products").then(
    (res) => res.json()
  );

  const categories = await fetch(
    "https://fakestoreapi.com/products/categories"
  ).then((res) => res.json());

  const productsGroupedByCategory = groupProductsByCategory(products);

  return {
    props: {
      products,
      categories,
      productsGroupedByCategory,
    },
  };
}
