//Next Js
import { GetServerSidePropsContext } from "next";
import Head from "next/head";
//Chakra
import { Box, Container } from "@chakra-ui/react";
//Components
import { Header } from "@/components/Headers";
import { TopBar } from "@/components/Topbar";

import { HomeHeroCategories } from "@/components/HomeHeroCategories";
import { Categories } from "@/models/Categories";

//Utilities



type Product = {
  id: number;
  title: string;
  price: number;
  description: string;
  category: string;
  image: string;
  rating: {
    rate: number;
    count: number;
  };
};

type Props = {
  products: Product[];
  categories: Categories[];
};

// this is executhe in the client side

export default function Home({ products, categories }: Props) {
  return (
    <>
      <Head>
        <title>E-Commerce Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <TopBar/>
        <Box marginBottom="2rem">
        <Header/>
        </Box>
        <Container size="lg">
        <HomeHeroCategories categories={categories}></HomeHeroCategories>
        </Container>
      </main>
    </>
  );
}
// This happen in the server side.
export async function getServerSideProps(contex: GetServerSidePropsContext) {
  const products = await fetch("https://fakestoreapi.com/products").then(
    (res) => res.json()
  );

  const categories = await fetch(
    "https://fakestoreapi.com/products/categories"
  ).then((res) => res.json());

  return {
    props: {
      products,
      categories,
    },
  };
}
